<?php
if(file_exists("models/Encryption.php")) include_once "models/Encryption.php";
else if(file_exists("../models/Encryption.php")) include_once "../models/Encryption.php";
else if (file_exists("../../models/Encryption.php")) include_once "../../models/Encryption.php";
if (file_exists("models/options.php")) include_once "models/options.php";
else if (file_exists("../models/options.php")) include_once "../models/options.php";
else if (file_exists("../../models/options.php")) include_once "../../models/options.php";
if (file_exists("models/optionvalues.php")) include_once "models/optionvalues.php";
else if (file_exists("../models/optionvalues.php")) include_once "../models/optionvalues.php";
else if (file_exists("../../models/optionvalues.php")) include_once "../../models/optionvalues.php";
if (file_exists("models/orderdetails.php")) include_once "models/orderdetails.php";
else if (file_exists("../models/orderdetails.php")) include_once "../models/orderdetails.php";
else if (file_exists("../../models/orderdetails.php")) include_once "../../models/orderdetails.php";
if (file_exists("models/orders.php")) include_once "models/orders.php";
else if (file_exists("../models/orders.php")) include_once "../models/orders.php";
else if (file_exists("../../models/orders.php")) include_once "../../models/orders.php";
if (file_exists("models/product.php")) include_once "models/product.php";
else if (file_exists("../models/product.php")) include_once "../models/product.php";
else if (file_exists("../../models/product.php")) include_once "../../models/product.php";
if (file_exists("models/productcategory.php")) include_once "models/productcategory.php";
else if (file_exists("../models/productcategory.php")) include_once "../models/productcategory.php";
else if (file_exists("../../models/productcategory.php")) include_once "../../models/productcategory.php";
if (file_exists("models/productcategoryoption.php")) include_once "models/productcategoryoption.php";
else if (file_exists("../models/productcategoryoption.php")) include_once "../models/productcategoryoption.php";
else if (file_exists("../../models/productcategoryoption.php")) include_once "../../models/productcategoryoption.php";
if (file_exists("models/user.php")) include_once "models/user.php";
else if (file_exists("../models/user.php")) include_once "../models/user.php";
else if (file_exists("../../models/user.php")) include_once "../../models/user.php";
if (file_exists("models/usertype.php")) include_once "models/usertype.php";
else if (file_exists("../models/usertype.php")) include_once "../models/usertype.php";
else if (file_exists("../../models/usertype.php")) include_once "../../models/usertype.php";
if (file_exists("models/data_base_ali.php")) include_once "models/data_base_ali.php";
else if (file_exists("../models/data_base_ali.php")) include_once "../models/data_base_ali.php";
else if (file_exists("../../models/data_base_ali.php")) include_once "../../models/data_base_ali.php";
if (file_exists("models/Buy_now.php")) include_once "models/Buy_now.php";
else if (file_exists("../models/Buy_now.php")) include_once "../models/Buy_now.php";
else if (file_exists("../../models/Buy_now.php")) include_once "../../models/Buy_now.php";
